default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hashbrown_development

test:
  <<: *default
  database: hashbrown_test

production:
  <<: *default
  database: hashbrown_production
